build:
  version: "1.0"

accounts:
  message: "Welcome to VatsBank accounts related to prod APIs "
  contactDetails:
    name: "Arya Tyagi - Developer"
    email: "arya@GM.com"
  onCallSupport:
    - (555) 555-1234
    - (555) 523-1345