build:
  version: "3.0"

cards:
  message: "Welcome to VatsBank cards related local APIs "
  contactDetails:
    name: "Dragos Lech - Developer"
    email: "dragos@gm.com"
  onCallSupport:
    - (412) 419-3491
    - (915) 382-1932