build:
  version: "2.0"

loans:
  message: "Welcome to VatsBank loans related QA APIs"
  contactDetails:
    name: "Amaal Grega - Developer"
    email: "amaal@eazybank.com"
  onCallSupport:
    - (452) 456-2176
    - (546) 764-8934